version: '3'

services:

  mysql_db:
    image: mariadb
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: wpbp
      MYSQL_DATABASE: wpbp
      MYSQL_USER: wpbp
      MYSQL_PASSWORD: wpbp
    networks:
      - app-network

  pma:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    networks:
      - app-network
    restart: always
    environment:
      PMA_HOST: mysql_db
    depends_on:
      - mysql_db

networks:
  app-network:
    driver: bridge
